import { describe, expect, it } from 'vitest';

import * as db from '../../packages/db/src/index';

describe('db package smoke', () => {
  it('exports a module surface', () => {
    expect(db).toBeTypeOf('object');
    expect(db.ORGANIZATIONS_TABLE).toBe('organizations');
    expect(db.ORGANIZATION_STATUSES).toContain('active');
    expect(db.ORGANIZATION_TYPES).toContain('shipwrecked_internal');
    expect(db.APP_USERS_TABLE).toBe('app_users');
    expect(db.APP_USER_STATUSES).toContain('invited');
    expect(db.APP_USER_PREFERRED_CONTACT_METHODS).toContain('push');
    expect(db.ORGANIZATION_MEMBERSHIPS_TABLE).toBe('organization_memberships');
    expect(db.ORGANIZATION_MEMBERSHIP_ROLES).toContain('technician');
    expect(db.ORGANIZATION_MEMBERSHIP_ADMIN_ROLES).toContain('owner');
    expect(db.ORGANIZATION_MEMBERSHIP_STATUSES).toContain('active');
    expect(db.LEADS_TABLE).toBe('leads');
    expect(db.LEAD_TYPES).toContain('commercial');
    expect(db.LEAD_STATUSES).toContain('qualified');
    expect(db.LEAD_SOURCES).toContain('website');
    expect(db.CUSTOMERS_TABLE).toBe('customers');
    expect(db.CUSTOMER_TYPES).toContain('commercial');
    expect(db.CUSTOMER_STATUSES).toContain('past_due');
    expect(db.CUSTOMER_ONBOARDING_STATUSES).toContain('in_progress');
    expect(db.CUSTOMER_BILLING_PROFILE_STATUSES).toContain('active');
    expect(db.HOUSEHOLD_MEMBERS_TABLE).toBe('household_members');
    expect(db.HOUSEHOLD_MEMBER_RELATIONSHIPS).toContain('spouse');
    expect(db.HOUSEHOLD_MEMBER_STATUSES).toContain('active');
    expect(db.HOUSEHOLD_MEMBER_ACCESS_LEVELS).toContain('manage_profile');
    expect(db.PROPERTIES_TABLE).toBe('properties');
    expect(db.PROPERTY_TYPES).toContain('commercial');
    expect(db.PROPERTY_STATUSES).toContain('paused');
    expect(db.PROPERTY_ACCESS_PROFILES_TABLE).toBe('property_access_profiles');
    expect(db.PROPERTY_ACCESS_PROFILE_STATUSES).toContain('inactive');
    expect(db.PROPERTY_ACCESS_TYPES).toContain('gate_code');
    expect(db.PETS_TABLE).toBe('pets');
    expect(db.PET_TYPES).toContain('dog');
    expect(db.PET_STATUSES).toContain('active');
    expect(db.PET_TEMPERAMENTS).toContain('friendly');
    expect(db.WATER_BODIES_TABLE).toBe('water_bodies');
    expect(db.WATER_BODY_TYPES).toContain('connected_spa');
    expect(db.WATER_BODY_STATUSES).toContain('paused');
    expect(db.WATER_BODY_SERVICE_STATUSES).toContain('active_service');
    expect(db.WATER_BODY_SANITIZER_TYPES).toContain('salt');
    expect(db.WATER_BODY_SURFACE_TYPES).toContain('pebble');
    expect(db.WATER_BODY_CHEMISTRY_PROFILE_STATUSES).toContain('ready');
    expect(db.WATER_BODY_RELATIONSHIPS_TABLE).toBe('water_body_relationships');
    expect(db.WATER_BODY_RELATIONSHIP_TYPES).toContain('connected_spa');
    expect(db.WATER_BODY_RELATIONSHIP_STATUSES).toContain('active');
  });
});
